#!/usr/bin/env python3
"""Generate the NWAI site mockup pages (shared styles + linked pages).
Output: Brain/_files/concepts/website-reposition-2026/site/
"""
import os, re, datetime

# Directory that holds the source mockups. This script lives in SRC/site, so derive
# SRC from the script's own location (was a hardcoded sandbox path that no longer exists).
SRC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(SRC, "site")
os.makedirs(OUT, exist_ok=True)

# ============================================================ SEO LAYER
# Standing rule (Wyatt, 2026-06-10): every page ships with a meta description,
# a self-referencing canonical, and OG/Twitter basics. robots.txt + sitemap.xml
# are generated by this build. The /claude Facebook LP stays meta noindex,nofollow,
# is NOT blocked in robots.txt (blocking crawl would hide the noindex from Google),
# and is NOT in the sitemap.
BASE = "https://nwai.co"
TODAY = datetime.date.today().isoformat()
WRITTEN = []  # filenames written this build, feeds sitemap.xml

def page_url(filename):
    return BASE + "/" if filename == "index.html" else BASE + "/" + filename[:-5] + "/"

SEO_DESC = {
  "index.html": "An entire AI team: a dedicated engineer builds your automations, we train your team on the best AI tools, and Company Brain manages your organizational context.",
  "company-brain.html": "An AI knowledge base for your business: Company Brain holds everything your AI needs to know, deployed to every employee and kept current. We run it, you own it.",
  "fractional-caio.html": "Fractional Chief AI Officer for mid-market companies: a fractional CAIO plus a dedicated engineer and trainer. Your whole AI team, without hiring one. $10M-$500M.",
  "claude-deployment.html": "Claude training and a 16-week AI deployment for your whole company, role by role, with working automations by the end. Fixed fee, scoped by headcount.",
  "workshops.html": "AI and Claude workshops for teams: hands-on training on the work your people actually do. One day or a short run, on-site or remote.",
  "ai-builds.html": "Custom AI agent and automation development, fixed scope and price. Phone agents, intake pipelines, and integrations, built and owned by you.",
  "case-study-referrals.html": "A healthcare provider sorted hundreds of insurance referrals by hand. We built a HIPAA-compliant pipeline tied to their EMR. Sorting now takes minutes.",
  "case-study-phone-agent.html": "A towing company fielding 500 calls a day was missing too many. Our phone agent now answers 90% of them, around the clock.",
  "case-study-safety-reports.html": "A commercial construction company had safety reports running 80% late. After our automation, 80% arrive on time, the paperwork that decides lawsuits.",
  "about.html": "Northwest AI started as an engineering shop in 2018 and bet the company on AI. Meet the team helping mid-market companies put AI to work.",
  "careers.html": "We're always hiring AI consultants, AI trainers, and engineers. Northwest AI hires people who know tech and can talk to humans.",
  "role-ai-consultant.html": "Embed with mid-market clients, map how their work actually flows, and put Claude to work on real operations. US-based.",
  "role-ai-trainer.html": "Deliver hands-on, role-specific AI training inside our 16-week deployment programs. US-based.",
  "role-engineer.html": "Build agents, pipelines, and Company Brain deployments for mid-market companies. Remote.",
  "privacy.html": "How Northwest AI Consulting collects, uses, and protects your information.",
  "terms.html": "The terms that govern use of Northwest AI Consulting's website and services.",
}

def seo_tags(filename, title):
    url = page_url(filename)
    desc = SEO_DESC[filename]
    return (
        '<meta name="description" content="%s">\n' % desc
        + '<link rel="canonical" href="%s">\n' % url
        + '<meta property="og:site_name" content="Northwest AI">\n'
        + '<meta property="og:type" content="website">\n'
        + '<meta property="og:title" content="%s">\n' % title
        + '<meta property="og:description" content="%s">\n' % desc
        + '<meta property="og:url" content="%s">\n' % url
        + '<meta name="twitter:card" content="summary">'
    )

# ---------- shared CSS: take v3's inline styles, add subpage styles ----------
v3 = open(os.path.join(SRC, "nwai-homepage-mockup-v3.html")).read()
base_css = re.search(r"<style>(.*?)</style>", v3, re.S).group(1)

extra_css = """
  /* ---- subpage additions ---- */
  .page-hero { padding: 90px 0 70px; border-top: none; }
  .page-hero h1 { font-size: clamp(36px, 5vw, 62px); max-width: 880px; margin-bottom: 24px; }
  .page-hero .lede { font-size: clamp(17px, 2vw, 20px); color: var(--ink-soft); max-width: 660px; }
  .page-hero .lede strong { color: var(--ink); }
  .prose { max-width: 720px; }
  .prose h2 { font-size: clamp(26px, 3.4vw, 38px); margin: 48px 0 18px; }
  .prose h2:first-child { margin-top: 0; }
  .prose p { font-size: 17px; color: var(--ink-soft); margin-bottom: 18px; }
  .prose p strong { color: var(--ink); }
  .prose ul { margin: 0 0 18px 22px; color: var(--ink-soft); font-size: 17px; }
  .prose li { margin-bottom: 8px; }
  .stat-strip { display: grid; grid-template-columns: repeat(3, 1fr); gap: 0; border-top: 1px solid var(--hairline); border-bottom: 1px solid var(--hairline); margin: 40px 0; }
  @media (max-width: 720px) { .stat-strip { grid-template-columns: 1fr; } }
  .stat-cell { padding: 28px 24px 28px 0; border-right: 1px solid var(--hairline-soft); }
  .stat-cell:last-child { border-right: none; }
  .stat-cell + .stat-cell { padding-left: 24px; }
  @media (max-width: 720px) { .stat-cell { border-right: none; padding-left: 0 !important; } }
  .stat-cell .n { font-family: "Fraunces", Georgia, serif; font-size: 30px; font-weight: 600; color: var(--terra); }
  .stat-cell .l { font-size: 13px; color: var(--ink-soft); margin-top: 4px; }
  .legal { max-width: 760px; }
  .legal h1 { font-size: clamp(32px, 4vw, 48px); margin-bottom: 10px; }
  .legal .updated { color: var(--ink-soft); font-size: 14px; margin-bottom: 40px; }
  .legal h2 { font-size: 22px; margin: 38px 0 12px; }
  .legal p, .legal li { font-size: 15.5px; color: var(--ink-soft); margin-bottom: 12px; }
  .legal ul { margin: 0 0 14px 22px; }
  .cta-band { background: var(--ink); color: var(--paper); border-radius: 16px; padding: 56px 48px; margin-top: 80px; }
  .cta-band h2 { color: var(--paper); font-size: clamp(26px, 3.4vw, 38px); max-width: 640px; margin-bottom: 14px; }
  .cta-band p { color: rgba(250,247,241,0.65); max-width: 540px; margin-bottom: 28px; font-size: 16.5px; }
  .cta-band em.acc { color: #E8916F; }
  .crumb { font-size: 13px; color: var(--ink-soft); margin-bottom: 20px; }
  .crumb a { color: var(--ink-soft); text-decoration: none; }
  .crumb a:hover { color: var(--ink); }
  .perm-grid { background: #fff; border: 1px solid var(--hairline); border-radius: 14px; overflow: hidden; margin: 36px 0; }
  .perm-head, .perm-row { display: grid; grid-template-columns: 1.4fr 1fr 1fr 1fr; }
  .perm-head { background: var(--paper); border-bottom: 1px solid var(--hairline); }
  .perm-head div { padding: 14px 18px; font-size: 12px; font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase; color: var(--ink-soft); }
  .perm-row { border-bottom: 1px solid var(--hairline-soft); }
  .perm-row:last-child { border-bottom: none; }
  .perm-row div { padding: 13px 18px; font-size: 14.5px; color: var(--ink-soft); }
  .perm-row div:first-child { font-family: "IBM Plex Mono", monospace; font-size: 13px; color: var(--ink); }
  .yes { color: #4F9D6F; font-weight: 700; }
  .no { color: var(--terra); font-weight: 700; }
  .note-flag { background: rgba(194,91,54,0.08); border: 1px dashed rgba(194,91,54,0.4); border-radius: 10px; padding: 18px 22px; font-size: 15px; color: var(--ink-soft); margin: 24px 0; }
  .note-flag strong { color: var(--terra); }
  .steps-vert { border-top: 1px solid var(--hairline); margin-top: 36px; }
  .step-v { display: grid; grid-template-columns: 90px 220px 1fr; gap: 28px; padding: 28px 0; border-bottom: 1px solid var(--hairline-soft); }
  @media (max-width: 760px) { .step-v { grid-template-columns: 1fr; gap: 6px; } }
  .step-v .num { font-family: "IBM Plex Mono", monospace; font-size: 13px; color: var(--terra); padding-top: 6px; }
  .step-v h3 { font-family: "Fraunces", Georgia, serif; font-size: 21px; font-weight: 600; }
  .step-v p { font-size: 15.5px; color: var(--ink-soft); max-width: 560px; }

  /* ---- context layer stack ---- */
  .stack { margin-top: 56px; position: relative; }
  .stack::before { content: ""; position: absolute; left: 31px; top: 18px; bottom: 18px; width: 2px; background: linear-gradient(var(--terra), rgba(194,91,54,0.15)); }
  .layer {
    position: relative; display: grid; grid-template-columns: 64px 150px 1fr 160px; gap: 20px; align-items: center;
    border: 1px solid var(--hairline); border-radius: 14px; padding: 26px 28px; margin-bottom: 14px;
    background: #fff;
  }
  .layer.l1 { background: var(--ink); border-color: var(--ink); margin-right: 0; }
  .layer.l2 { background: var(--paper-2); margin-right: 56px; }
  .layer.l3 { background: #fff; margin-right: 112px; }
  @media (max-width: 860px) { .layer { grid-template-columns: 48px 1fr; margin-right: 0 !important; } .layer .l-note { grid-column: 2; } .layer p { grid-column: 1 / -1; } .stack::before { display: none; } }
  .layer .l-chip {
    width: 40px; height: 40px; border-radius: 10px; display: flex; align-items: center; justify-content: center;
    font-family: "IBM Plex Mono", monospace; font-size: 13px; font-weight: 700;
    background: var(--terra); color: #fff; position: relative; z-index: 1;
  }
  .layer.l2 .l-chip { background: rgba(194,91,54,0.85); }
  .layer.l3 .l-chip { background: rgba(194,91,54,0.65); }
  .layer h3 { font-family: "Fraunces", Georgia, serif; font-size: 21px; font-weight: 600; color: var(--ink); }
  .layer.l1 h3 { color: var(--paper); }
  .layer p { font-size: 15px; color: var(--ink-soft); margin: 0; }
  .layer.l1 p { color: rgba(250,247,241,0.7); }
  .layer .l-note {
    font-size: 11px; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase;
    color: var(--terra); text-align: right;
  }
  .layer.l1 .l-note { color: #E8916F; }

  /* result numerals: ink, accent only on the after-state */
  .result-row .n { color: var(--ink); }
  .result-row .n em { font-style: normal; color: var(--terra); }

  /* ---- press ticker (Corgi-style) ---- */
  .pressticker { background: var(--paper); border-top: 1px solid var(--hairline-soft); padding: 36px 0 30px; overflow: hidden; }
  .tk-track { display: flex; align-items: flex-start; width: max-content; animation: tkscroll 48s linear infinite; }
  .pressticker:hover .tk-track { animation-play-state: paused; }
  .tk-item { display: flex; flex-direction: column; align-items: center; gap: 7px; padding: 0 48px; white-space: nowrap; border-right: 1px solid var(--hairline-soft); }
  .tk-mark { font-weight: 800; font-size: 23px; color: var(--ink); line-height: 1; }
  .tk-cap { font-size: 11px; color: var(--ink-soft); }
  .tk-logo { display: block; width: auto; height: auto; max-height: 30px; max-width: 150px; object-fit: contain; filter: grayscale(1); opacity: 0.8; }
  .tk-item { justify-content: flex-end; min-height: 52px; }
  @keyframes tkscroll { from { transform: translateX(0); } to { transform: translateX(-50%); } }
  @media (prefers-reduced-motion: reduce) { .tk-track { animation: none; flex-wrap: wrap; width: auto; } }

  /* ---- nav dropdowns ---- */
  .menu-item { position: relative; }
  .menu-item > a.top {
    color: var(--ink-soft); text-decoration: none; font-size: 14.5px; font-weight: 500;
    display: inline-flex; align-items: center; gap: 5px; padding: 8px 0;
  }
  .menu-item > a.top:hover { color: var(--ink); }
  .menu-item > a.top .car { font-size: 9px; opacity: 0.6; transform: translateY(1px); }
  .dropdown {
    position: absolute; top: 100%; left: -18px; min-width: 280px;
    background: #fff; border: 1px solid var(--hairline); border-radius: 12px;
    box-shadow: 0 18px 44px -18px rgba(32, 40, 58, 0.28);
    padding: 10px; display: none; z-index: 60;
  }
  .menu-item:hover .dropdown, .menu-item:focus-within .dropdown { display: block; }
  .dropdown a {
    display: block; padding: 11px 14px; border-radius: 8px; text-decoration: none;
    color: var(--ink) !important; font-size: 14.5px !important; font-weight: 600;
  }
  .dropdown a .d { display: block; font-weight: 400; font-size: 12.5px; color: var(--ink-soft); margin-top: 2px; }
  .dropdown a:hover { background: var(--paper); }
  .dropdown .dd-label {
    padding: 8px 14px 4px; font-size: 10.5px; font-weight: 700; letter-spacing: 0.14em;
    text-transform: uppercase; color: var(--ink-soft);
  }
  .dropdown hr { border: none; border-top: 1px solid var(--hairline-soft); margin: 8px 6px; }

  /* ---- mobile nav: hamburger drawer (added 2026-06-29) ---- */
  .nav-toggle { display: none; background: none; border: none; cursor: pointer; color: var(--ink); padding: 6px; margin: -6px 0; line-height: 0; -webkit-tap-highlight-color: transparent; }
  @media (max-width: 800px) {
    .nav-toggle { display: inline-flex; align-items: center; }
    .nav-links {
      display: none; position: absolute; top: 100%; left: 0; right: 0;
      flex-direction: column; align-items: stretch; gap: 0;
      background: var(--paper); border-top: 1px solid var(--hairline); border-bottom: 1px solid var(--hairline);
      padding: 6px 0 16px; max-height: calc(100vh - 70px); overflow-y: auto;
      box-shadow: 0 26px 40px -26px rgba(32,40,58,0.45);
    }
    .nav-links.open { display: flex; }
    .nav-links.open a:not(.btn) { display: block; }
    .menu-item { width: 100%; }
    .menu-item > a.top { display: flex; justify-content: space-between; align-items: center; padding: 13px 36px; font-size: 16px; color: var(--ink); }
    .menu-item > a.top .car { opacity: 0.5; }
    .nav-links.open .dropdown { position: static; display: block; box-shadow: none; border: none; min-width: 0; padding: 0 36px 10px; border-radius: 0; }
    .nav-links.open .dropdown a { padding: 9px 0 !important; }
    .dropdown .dd-label { padding: 8px 0 4px; }
    .dropdown hr { margin: 8px 0; }
    .nav-links .btn { display: block; margin: 14px 36px 4px; text-align: center; }
  }

  /* ---- prevent horizontal scroll on mobile (added 2026-06-29) ---- */
  html, body { overflow-x: clip; }
  table { table-layout: fixed; }
  td, th { overflow-wrap: anywhere; }

  /* ---- mobile: tighten hero top gap + keep comparison table readable (added 2026-06-29) ---- */
  @media (max-width: 800px) { .hero { padding-top: 48px; padding-bottom: 64px; } }
  .table-scroll { overflow-x: auto; -webkit-overflow-scrolling: touch; }
  @media (max-width: 760px) {
    .compare .table-scroll table { min-width: 520px; }
    .compare td, .compare th { padding: 14px 16px; }
  }
"""

open(os.path.join(OUT, "styles.css"), "w").write(base_css + extra_css)

# ---------- shared nav / footer ----------
NAV = """<nav>
  <div class="wrap nav-inner">
    <a class="logo" href="/">Northwest AI<span class="dot">.</span></a>
    <button class="nav-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="nav-links">
      <svg width="26" height="26" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>
    </button>
    <div class="nav-links" id="nav-links">
      <div class="menu-item">
        <a class="top" href="#">What we do <span class="car">&#9660;</span></a>
        <div class="dropdown">
          <div class="dd-label">Programs</div>
          <a href="fractional-caio.html">Your AI Team<span class="d">A dedicated engineer, an AI lead, and a trainer, run for you</span></a>
          <a href="claude-deployment.html">Deployment Program<span class="d">Company-wide Claude rollout in 16 weeks</span></a>
          <a href="workshops.html">AI Workshops<span class="d">Hands-on training, one team at a time</span></a>
          <a href="ai-builds.html">AI Builds<span class="d">One custom system, fixed scope and price</span></a>
          <hr>
          <div class="dd-label">Product</div>
          <a href="company-brain.html">Company Brain<span class="d">The context system behind everything we deploy</span></a>
        </div>
      </div>
      <div class="menu-item">
        <a class="top" href="index.html#results">Results <span class="car">&#9660;</span></a>
        <div class="dropdown">
          <a href="case-study-referrals.html">Insurance referrals: hours to minutes<span class="d">Healthcare</span></a>
          <a href="case-study-phone-agent.html">A phone agent for 500 daily calls<span class="d">Towing &amp; logistics</span></a>
          <a href="case-study-safety-reports.html">Safety reports: 80% late to 80% on time<span class="d">Construction</span></a>
          <hr>
          <a href="index.html#results">All results &rarr;</a>
        </div>
      </div>
      <div class="menu-item">
        <a class="top" href="about.html">Company <span class="car">&#9660;</span></a>
        <div class="dropdown">
          <a href="about.html">About<span class="d">Who we are and what we believe</span></a>
          <a href="careers.html">Careers<span class="d">AI consultants, trainers, and engineers</span></a>
          <a href="index.html#book">Contact<span class="d">Book a call or reach the team</span></a>
        </div>
      </div>
      <a class="btn" href="index.html#book">Book a call</a>
    </div>
  </div>
</nav>
<script>
(function(){
  var b=document.querySelector('.nav-toggle'), l=document.getElementById('nav-links');
  if(!b||!l) return;
  function set(o){ l.classList.toggle('open', o); b.setAttribute('aria-expanded', o?'true':'false'); b.setAttribute('aria-label', o?'Close menu':'Open menu'); }
  b.addEventListener('click', function(){ set(!l.classList.contains('open')); });
  l.addEventListener('click', function(e){ if(e.target.closest('a')) set(false); });
})();
</script>"""

PRESS = [
    ("zdnet",        '<span class="tk-mark" style="font-weight:900; letter-spacing:0.02em;">ZDNET</span>', "As covered in ZDNET, Sep 2025."),
    ("uschamber",    '<span class="tk-mark" style="font-family: Georgia, serif; font-weight:600; font-size:17px; letter-spacing:0.06em;">U.S. CHAMBER OF COMMERCE</span>', "As covered by the U.S. Chamber of Commerce, Jul 2025."),
    ("computerworld",'<span class="tk-mark" style="text-transform: lowercase;">computerworld</span>', "As covered in Computerworld, Oct 2025."),
    ("thestreet",    '<span class="tk-mark">TheStreet</span>', "As covered in TheStreet, Jul 2025."),
    ("infoworld",    '<span class="tk-mark">InfoWorld</span>', "As covered in InfoWorld, Jul 2025."),
    ("pymnts",       '<span class="tk-mark" style="font-weight:900; letter-spacing:0.08em;">PYMNTS</span>', "As covered in PYMNTS, Jul 2025."),
    ("hubspot",      '<span class="tk-mark">HubSpot</span>', "As covered by HubSpot, Oct 2025."),
    ("cso",          '<span class="tk-mark">CSO <span style="font-weight:500; font-size:15px;">ONLINE</span></span>', "As covered in CSO Online, Sep 2025."),
    ("cio",          '<span class="tk-mark" style="font-weight:900; letter-spacing:0.05em;">CIO</span>', "As covered in CIO, Feb 2026."),
]
SIZES = {
    "cio": "max-height: 36px;",
    "zdnet": "max-height: 36px;",
    "uschamber": "max-height: 32px; max-width: 170px;",
    "computerworld": "max-height: 26px; max-width: 200px;",
}
def build_ticker():
    rows = []
    for slug, fallback, cap in PRESS:
        mark = fallback
        for ext in ("png", "webp", "jpg", "svg"):
            if os.path.exists(os.path.join(OUT, "logos", slug + "." + ext)):
                style = SIZES.get(slug, "")
                mark = '<img class="tk-logo" src="logos/{0}.{1}" alt="{0} logo" style="{2}">'.format(slug, ext, style)
                break
        rows.append('      <div class="tk-item">' + mark + '<span class="tk-cap">' + cap + '</span></div>')
    items = "\n".join(rows) + "\n"
    return '<div class="pressticker">\n  <div class="tk-track">\n' + items + items + '  </div>\n</div>\n\n'

FOOTER = """{{PRESSTICKER}}<footer>
  <div class="wrap foot-rule">
    <div class="foot-inner">
      <div>
        <div class="foot-logo">Northwest AI<span class="dot">.</span></div>
        <div style="margin-top: 10px;">830 NE Holladay St, Suite 1325, Portland, OR 97232<br>
        <a href="mailto:wyatt@nwai.co">wyatt@nwai.co</a> &middot; <a href="tel:+15032984673">503-298-4673</a></div>
      </div>
      <div class="foot-links" style="flex-direction: column; gap: 8px;">
        <strong style="color: rgba(250,247,241,0.8); font-size: 13px; letter-spacing: 0.1em; text-transform: uppercase;">Programs</strong>
        <a href="fractional-caio.html">Your AI Team</a>
        <a href="claude-deployment.html">Claude Deployment Program</a>
        <a href="workshops.html">AI Workshops</a>
        <a href="ai-builds.html">AI Builds</a>
        <a href="company-brain.html">Company Brain</a>
      </div>
      <div class="foot-links" style="flex-direction: column; gap: 8px;">
        <strong style="color: rgba(250,247,241,0.8); font-size: 13px; letter-spacing: 0.1em; text-transform: uppercase;">Case studies</strong>
        <a href="case-study-referrals.html">Insurance referrals: hours to minutes</a>
        <a href="case-study-phone-agent.html">A phone agent for 500 daily calls</a>
        <a href="case-study-safety-reports.html">Safety reports: 80% late to 80% on time</a>
      </div>
      <div class="foot-links" style="flex-direction: column; gap: 8px;">
        <strong style="color: rgba(250,247,241,0.8); font-size: 13px; letter-spacing: 0.1em; text-transform: uppercase;">Company</strong>
        <a href="about.html">About</a>
        <a href="careers.html">Careers</a>
        <a href="privacy.html">Privacy</a>
        <a href="terms.html">Terms</a>
      </div>
    </div>
    <div style="margin-top: 30px; font-size: 12.5px; opacity: 0.5;">&copy; 2026 Northwest AI. All rights reserved.</div>
  </div>
</footer>"""
FOOTER = FOOTER.replace("{{PRESSTICKER}}", build_ticker())


HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{TITLE}}</title>
{{SEO}}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,500;0,9..144,600;1,9..144,400;1,9..144,500;1,9..144,600&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="styles.css">
<!-- iClosed popup widget begin -->
<script type="text/javascript" src="https://app.iclosed.io/assets/widget.js" async></script>
<!-- iClosed popup widget end -->
</head>
<body>
"""

# --- Tracking: GTM container + Facebook domain verification (added 2026-06-16) ---
# Only the GTM container loads on the page. Every conversion/analytics tag (Google Ads
# AW-17331670664, GA4 G-V0ZJ5KTEAA, Meta Pixel, etc.) fires INSIDE the GTM container, so
# none of those are hardcoded here. Hardcoding them too would double-count conversions.
# GTM is the single source for those events.
FB_META = '<meta name="facebook-domain-verification" content="uvurknwfoozz7aou0s49waz7rdd54y" />'
GTM_HEAD = """<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-56W2P5N8');</script>
<!-- End Google Tag Manager -->"""
GTM_NOSCRIPT = """<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-56W2P5N8"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->"""

# Favicon / app icons (added 2026-06-28). Files live at the site root; Vercel serves them at /.
FAVICON = """<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="theme-color" content="#20283A">"""

# Inject into the shared template so every current and future page carries it.
HEAD = HEAD.replace("<head>", "<head>\n" + FAVICON + "\n" + FB_META + "\n" + GTM_HEAD, 1)
HEAD = HEAD.replace("<body>", "<body>\n" + GTM_NOSCRIPT, 1)

# Every booking CTA opens the iClosed popup (element-click embed)
ICLOSED = 'href="javascript:void(0)" data-iclosed-link="https://app.iclosed.io/e/nwai/book-a-call" data-embed-type="popup"'
def wire_booking(html):
    html = html.replace('href="index.html#book"', ICLOSED)
    html = html.replace('href="#book"', ICLOSED)
    html = html.replace('<a class="btn terra" href="#">Book a discovery call</a>',
                        '<a class="btn terra" ' + ICLOSED + '>Book a discovery call</a>')
    return html

# Headshots ship from the repo (images/) instead of hotlinked from nwai.co, which blocks
# cross-origin loads and broke them for visitors. Added 2026-06-29.
FACE_MAP = {
    "https://nwai.co/wp-content/uploads/2025/07/wyatt-headshot-hq-2.png": "images/wyatt-headshot.png",
    "https://nwai.co/wp-content/uploads/2025/07/asad-headshot.jpg": "images/asad-headshot.webp",
    "https://nwai.co/wp-content/uploads/2025/07/awais-headshot.jpg": "images/awais-headshot.jpg",
}
def localize_faces(html):
    for remote, local in FACE_MAP.items():
        html = html.replace(remote, local)
    return html

CTA_BAND = """<div class="wrap"><div class="cta-band">
  <h2>Find out what this looks like <em class="acc">in your company.</em></h2>
  <p>One call. We'll tell you exactly what AI can and can't do for your business, and what it would take. If it's not a fit, we'll say so.</p>
  <a class="btn terra" href="index.html#book">Book a discovery call</a>
</div></div>
"""

def page(filename, title, body, include_cta=True):
    title = title.replace(" — ", " · ")  # no em dashes, incl. title tags (Wyatt)
    html = HEAD.replace("{{TITLE}}", title).replace("{{SEO}}", seo_tags(filename, title)) + NAV + body
    if include_cta:
        html += CTA_BAND
    html += "\n<div style='height:80px'></div>\n" + FOOTER + "\n</body>\n</html>\n"
    html = wire_booking(html)
    html = localize_faces(html)
    html = html.replace("wyatt@nwai.co", "consulting@nwai.co")
    open(os.path.join(OUT, filename), "w").write(html)
    WRITTEN.append(filename)
    print("wrote", filename)

# ============================================================ COMPANY BRAIN
company_brain = """
<header class="page-hero">
  <div class="wrap">
    <div class="kicker">Our product &middot; Company Brain</div>
    <h1>AI gives generic answers until it <em class="acc">knows your company.</em></h1>
    <p class="lede">Company Brain is our context management system. It holds everything AI needs to know about your business, defined once, deployed to every employee, and kept current. <strong>We run it. You own it.</strong></p>
  </div>
</header>

<section>
  <div class="wrap">
    <div class="kicker">The problem it solves</div>
    <div class="prose">
      <h2>Watch any company's AI usage and you'll see the same pattern.</h2>
      <p>The people most skeptical of change open AI, ask a question about their work, and get a generic answer, because the AI knows nothing about the company. They quit using it within the week. That's where most rollouts die.</p>
      <p>The standard fix is to make every employee load company context themselves: build folder structures, learn what an index file is, decide what the AI should know. <strong>Nobody in sales, operations, or finance wants a course on folder structures.</strong> So instead, people mount everything, burn through usage on noise, still get generic answers, and give up.</p>
      <p>The companies that get AI working solve context once, centrally, for everyone. That's what Company Brain does.</p>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">What it is</div>
    <h2 style="max-width: 800px;">One governed structure for everything your <em class="acc">AI needs to know.</em></h2>
    <div class="brain-grid" style="margin-top: 48px;">
      <div class="brain-copy">
        <p><strong>Your company's knowledge, mapped to where it actually lives.</strong> SharePoint, Google Drive, GitHub, Notion, your data warehouse. Company Brain doesn't move your files. It builds one clean structure on top of them and keeps the two in sync.</p>
        <p><strong>Pushed to every employee.</strong> When your people open Claude, the right context for their role is already there. Nobody sets up anything. Nobody learns anything technical.</p>
        <p><strong>Centrally controlled.</strong> Your admin or AI champion edits in one place and it updates for the whole company. Core facts about the business stay locked so the source of truth stays true.</p>
      </div>
      <div>
      <div class="panel">
        <div class="panel-bar">
          <span class="t">Acme Co &middot; Company Brain</span>
          <span class="status"><span class="dotg"></span>Kept current</span>
        </div>
        <div class="panel-body">
          <div class="pb-row"><span class="f">company-overview</span><span class="src">SharePoint</span></div>
          <div class="pb-row"><span class="f">sales/</span><span class="src hot">Drive</span></div>
          <div class="pb-row"><span class="f">projects/</span><span class="src">SharePoint</span></div>
          <div class="pb-row"><span class="f">customers/</span><span class="src">Notion</span></div>
          <div class="pb-row"><span class="f">finance/</span><span class="src hot">Data warehouse</span></div>
          <div class="pb-row"><span class="f">operations/</span><span class="src">SharePoint</span></div>
        </div>
        <div class="panel-foot">One structure, mapped to where your knowledge already lives, pushed to every employee by role.</div>
      </div>
      <p class="mock-note" style="font-size: 12px; color: var(--ink-soft); margin-top: 12px; opacity: 0.8;">Illustration with example data.</p>
      </div>
    </div>
    <div class="stack">
      <div class="layer l1">
        <div class="l-chip">L1</div>
        <h3>Company</h3>
        <p>Who you are, what you build, who you sell to, what's confidential, voice and house rules. The always-true layer.</p>
        <div class="l-note">Locked &middot; stays true</div>
      </div>
      <div class="layer l2">
        <div class="l-chip">L2</div>
        <h3>Department</h3>
        <p>SOPs, data sources, tools, repeating outputs. The way finance actually closes the books, the way sales actually quotes.</p>
        <div class="l-note">Curated with your leads</div>
      </div>
      <div class="layer l3">
        <div class="l-chip">L3</div>
        <h3>Individual</h3>
        <p>Role-specific files, recurring tasks, personal voice, the workflows each operator owns. The layer that makes Claude feel like theirs.</p>
        <div class="l-note">Each operator's own</div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="kicker">Access by role</div>
    <h2 style="max-width: 760px;">Everyone gets the context they need. <em class="acc">Nothing they shouldn't have.</em></h2>
    <p style="color: var(--ink-soft); max-width: 640px; margin-top: 16px; font-size: 17px;">Executives see the whole company. A project manager sees their projects, not the finance folders. Leadership decides who sees what, once, and Company Brain enforces it everywhere.</p>
    <div class="perm-grid">
      <div class="perm-head"><div>Context</div><div>Executive</div><div>Sales</div><div>Operations</div></div>
      <div class="perm-row"><div>company-overview/</div><div class="yes">&#10003;</div><div class="yes">&#10003;</div><div class="yes">&#10003;</div></div>
      <div class="perm-row"><div>sales/</div><div class="yes">&#10003;</div><div class="yes">&#10003;</div><div class="no">&#10007;</div></div>
      <div class="perm-row"><div>operations/</div><div class="yes">&#10003;</div><div class="no">&#10007;</div><div class="yes">&#10003;</div></div>
      <div class="perm-row"><div>finance/</div><div class="yes">&#10003;</div><div class="no">&#10007;</div><div class="no">&#10007;</div></div>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">How it gets built</div>
    <h2>You never think about it. <em class="acc">That's the point.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">01</div><h3>Define</h3><p>Week one, we sit with your leadership and the people who run each department. We pull the 20% of context that drives 80% of the value out of their heads and systems. Your team doesn't interview 500 people. We talk to the few who know.</p></div>
      <div class="step-v"><div class="num">02</div><h3>Map</h3><p>We connect the structure to where your knowledge actually lives: SharePoint, Google Drive, GitHub, Notion, your databases. Big datasets pipe in from the warehouse. Nothing gets migrated.</p></div>
      <div class="step-v"><div class="num">03</div><h3>Deploy</h3><p>The right context lands on every employee's Claude, matched to their role, along with pre-built skills for their actual workflows. Day one, the AI already knows the business.</p></div>
      <div class="step-v"><div class="num">04</div><h3>Run</h3><p>We keep it current as your business changes. Your admins edit anything, anytime, in one place. New skills and updates push to the whole company without anyone lifting a finger.</p></div>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="prose">
      <h2>Why this is the part that <em class="acc">compounds.</em></h2>
      <p>Custom agents are powerful. Training sticks. But context is what makes every single AI interaction in your company better, for every employee, on day one. It's the difference between AI as a toy and AI as how work gets done.</p>
      <p>And it's yours. The structure, the content, the source mappings all live in your environment. We run it while we're engaged. If you ever leave, it stays.</p>
    </div>
  </div>
</section>
"""
page("company-brain.html", "Company Brain: AI Knowledge Base — Northwest AI", company_brain)

# ============================================================ FRACTIONAL CAIO
fcaio = """
<header class="page-hero">
  <div class="wrap">
    <div class="kicker">Programs &middot; Your AI Team</div>
    <h1>An entire AI team. <em class="acc">Without hiring one.</em></h1>
    <p class="lede">An AI lead, a dedicated engineer, and a trainer, embedded in your company every month. <strong>The fastest way to make your company AI native.</strong></p>
    <div class="hero-cta" style="margin-top: 32px;"><a class="btn terra" href="index.html#book">Book a discovery call</a></div>
  </div>
</header>

<section>
  <div class="wrap">
    <div class="kicker">Sound familiar?</div>
    <h2 style="max-width: 820px;">You bought AI. <em class="acc">The work still gets done by hand.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Time</div><h3>Your best people do robot work</h3><p>Hours a week copying numbers between systems, sorting an inbox, rebuilding the same report by hand.</p></div>
      <div class="step-v"><div class="num">Adoption</div><h3>You rolled out AI. Nothing changed.</h3><p>A few people use it. The actual day-to-day still runs the old way, with a chatbot open in another tab.</p></div>
      <div class="step-v"><div class="num">Bottleneck</div><h3>Your AI champion is maxed out</h3><p>One smart person became your whole AI capability, and now every project waits on them.</p></div>
      <div class="step-v"><div class="num">Competition</div><h3>Someone is pulling ahead</h3><p>A competitor does more with fewer people, and you can't quite see what they're doing differently.</p></div>
    </div>
    <p style="color: var(--ink-soft); margin-top: 24px; font-size: 17px;">That's the AI Gap. It compounds every quarter you wait.</p>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">The real game</div>
    <div class="prose">
      <h2>Stop growing by hiring. <em class="acc">Grow per head.</em></h2>
      <p>Most companies have one lever for growth: add people. Automate the busywork and the same team produces far more, at better margins. That's the whole game. Revenue per head, not headcount, and it's what an AI team actually buys you.</p>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="kicker">What you get</div>
    <h2 style="max-width: 800px;">Not a workshop. Not a course. <em class="acc">A team that ships.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">01</div><h3>An AI lead</h3><p>Owns your whole AI plan. Finds the wins, sets the priorities, makes sure it ships. Your fractional Chief AI Officer.</p></div>
      <div class="step-v"><div class="num">02</div><h3>A dedicated engineer</h3><p>Yours full- or half-time. Builds what off-the-shelf AI can't: phone agents, intake pipelines, the systems that don't talk. You own every line.</p></div>
      <div class="step-v"><div class="num">03</div><h3>Your team, fluent in AI</h3><p>We train every person on their real work, with the best tool for the job, until they find their own wins.</p></div>
      <div class="step-v"><div class="num">04</div><h3>Your Company Brain</h3><p>All your data and know-how in one place your AI runs on. Nobody enters the same number twice. <a href="company-brain.html" style="color: var(--terra);">How it works &rarr;</a></p></div>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">How it runs</div>
    <h2>Month one ships. <em class="acc">Then it just runs.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Month 1</div><h3>The 80/20, included</h3><p>We map your work and rank where AI pays off fastest. That becomes your build list.</p></div>
      <div class="step-v"><div class="num">Sprints</div><h3>Two-week sprints you can see</h3><p>Your engineer works a board you control. Weekly check-in, reprioritize anytime. No hours, no credits.</p></div>
      <div class="step-v"><div class="num">Weekly</div><h3>Training and a Slack line</h3><p>Role-by-role training on real work, plus a Slack channel to your team whenever you need it.</p></div>
      <div class="step-v"><div class="num">The deal</div><h3>Annual, guaranteed</h3><p>Three tiers, billed monthly, 60-day money-back. Add engineers as you grow.</p></div>
    </div>
    <div class="stat-strip">
      <div class="stat-cell"><div class="n">Week 1</div><div class="l">Your team is live</div></div>
      <div class="stat-cell"><div class="n">Month 1</div><div class="l">80/20 Report in hand</div></div>
      <div class="stat-cell"><div class="n">60-day</div><div class="l">Money-back guarantee</div></div>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="kicker">Proof</div>
    <h2 style="max-width: 800px;">We've done this <em class="acc">100+ times.</em></h2>
    <p style="color: var(--ink-soft); margin: 14px 0 8px; font-size: 17px;">Same fix, across very different industries:</p>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Healthcare</div><h3>Hours to minutes</h3><p>Referral sorting that ate hours a day, now minutes. HIPAA, tied straight into their EMR. <a href="case-study-referrals.html" style="color: var(--terra);">Read it &rarr;</a></p></div>
      <div class="step-v"><div class="num">Towing</div><h3>90% of 500 calls a day</h3><p>A phone agent answering nine of ten calls, around the clock. <a href="case-study-phone-agent.html" style="color: var(--terra);">Read it &rarr;</a></p></div>
      <div class="step-v"><div class="num">Construction</div><h3>80% late to 80% on time</h3><p>The safety paperwork that decides lawsuits, finally filed on time. <a href="case-study-safety-reports.html" style="color: var(--terra);">Read it &rarr;</a></p></div>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">The math</div>
    <div class="prose">
      <h2>Hire this team yourself? <em class="acc">Over $1M a year.</em></h2>
      <p>An AI leader who has actually run rollouts, a dedicated engineer, and a trainer add up to well over a million a year in salary, before they ship a thing, and that's if you can even find them. You get all three for one monthly fee, and you own everything they build.</p>
    </div>
    <div class="stat-strip">
      <div class="stat-cell"><div class="n">$1M+/yr</div><div class="l">To hire the three roles</div></div>
      <div class="stat-cell"><div class="n">One fee</div><div class="l">For the whole team, monthly</div></div>
      <div class="stat-cell"><div class="n">You own it</div><div class="l">Every line, every workflow</div></div>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="kicker">Who it's for</div>
    <div class="prose"><h2>Built for the companies big firms <em class="acc">can't serve.</em></h2></div>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Size</div><h3>$10M to $500M</h3><p>Under $10M, the math doesn't work yet. We'll tell you straight and point you to our free content.</p></div>
      <div class="step-v"><div class="num">Industry</div><h3>The real economy</h3><p>Construction, insurance, energy, manufacturing, healthcare, and more. The less digital, the bigger your head start.</p></div>
      <div class="step-v"><div class="num">Best fit</div><h3>Someone at the top wants this</h3><p>It works when a leader is bought in and ready to make AI actually happen, not just buy the tool.</p></div>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">Questions</div>
    <h2>The ones we <em class="acc">actually get.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Busy?</div><h3>"It's our busy season."</h3><p>Every season is. Fix the busywork now and the busy ones get easier, not harder.</p></div>
      <div class="step-v"><div class="num">DIY?</div><h3>"We'll try it internally first."</h3><p>Your champion already has a full-time job. Our team plus your people beats either alone, and we pick up wherever you got to.</p></div>
      <div class="step-v"><div class="num">Vendor?</div><h3>"We already have a dev shop."</h3><p>Good. We own AI alongside them. The best results usually have more than one source of help.</p></div>
      <div class="step-v"><div class="num">Price?</div><h3>"How much is it?"</h3><p>Three tiers, billed monthly, month one included, 60-day money-back. We give you the number on the first call.</p></div>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="kicker">The risk is ours</div>
    <div class="prose">
      <h2>60 days. <em class="acc">Or your money back.</em></h2>
      <p>If we haven't delivered clear value in the first 60 days, you get a full refund, and you keep the discovery, the trained team, and the 80/20 roadmap. The risk is on us, not you.</p>
    </div>
  </div>
</section>
"""
page("fractional-caio.html", "Fractional Chief AI Officer & AI Team — Northwest AI", fcaio)

# ============================================================ CLAUDE DEPLOYMENT
cdp = """
<header class="page-hero">
  <div class="wrap">
    <div class="kicker">Programs &middot; Claude Deployment Program</div>
    <h1>Your whole company on Claude, doing real work, <em class="acc">in 16 weeks.</em></h1>
    <p class="lede">A fixed-scope, fixed-fee program built on three pillars: <strong>executive training, department-by-department rollout with matched consultants, and the context architecture that makes adoption stick.</strong> It ends with your people demoing real automations they built.</p>
    <div class="hero-cta" style="margin-top: 32px;"><a class="btn terra" href="index.html#book">Book a discovery call</a></div>
  </div>
</header>

<section>
  <div class="wrap">
    <div class="kicker">The three pillars</div>
    <h2 style="max-width: 820px;">Three pillars. <em class="acc">One cadence.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">01</div><h3>Executives first</h3><p>Your exec team trains alongside the org, with a consultant who has worked on exec teams, in the language of budgets and board updates, not prompt theory. We used to make this optional. We don't anymore: adoption only sticks when the workforce sees leadership using it first.</p></div>
      <div class="step-v"><div class="num">02</div><h3>Matched consultants</h3><p>Each department pairs with a consultant who actually did that job: finance with a finance veteran, sales with a sales veteran, ops with an ops veteran. They speak the operators' language and know where Claude breaks in practice, not in theory.</p></div>
      <div class="step-v"><div class="num">03</div><h3>Context architecture</h3><p>Company, department, and individual-level knowledge wired into Claude, built as its own parallel workstream so we never burn a training session on troubleshooting someone's folder sync. <a href="company-brain.html" style="color: var(--terra);">This is Company Brain &rarr;</a></p></div>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">The 16 weeks</div>
    <h2>Foundations, capability, possibility, <em class="acc">builds.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Weeks 0&ndash;3</div><h3>Foundations</h3><p>Everyone gets to the same baseline: procurement and settings, then Claude 101 and 102. Nobody starts department work behind.</p></div>
      <div class="step-v"><div class="num">Weeks 4&ndash;9</div><h3>Context + capability</h3><p>The context substrate goes in, then weekly tool mastery: Excel, documents and decks, artifacts, skills. Your people stop chatting with AI and start working with it.</p></div>
      <div class="step-v"><div class="num">Weeks 10&ndash;11</div><h3>What's possible</h3><p>Show, then ask. Curated examples from past clients in your industry, walked through end to end, so your team sees the bar before they're asked to clear it.</p></div>
      <div class="step-v"><div class="num">Weeks 12&ndash;16</div><h3>Pod builds + demo day</h3><p>Pair-programming with the matched consultant. By week 16 your people ship real automations they own, demoed at a final readout with ROI. An invite-only advanced group runs in parallel for the top users: Claude Code, MCP, agentic workflows.</p></div>
    </div>
    <div class="stat-strip" style="margin-top: 44px;">
      <div class="stat-cell"><div class="n">60+</div><div class="l">Named deliverables across 16 weeks</div></div>
      <div class="stat-cell"><div class="n">3&ndash;5</div><div class="l">Departments, scoped by headcount</div></div>
      <div class="stat-cell"><div class="n">Demo day</div><div class="l">Your people present what they built</div></div>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="kicker">The honest part</div>
    <h2 style="max-width: 800px;">We're going to ask something <em class="acc">of your team.</em></h2>
    <div class="prose" style="margin-top: 24px;">
      <p>Real workforce adoption isn't free, and we put this in writing before kickoff. Your people commit <strong>4 to 6 hours a month</strong> of workshop time, pair-programming, and homework on their own files. The first three weeks feel like learning a new operating system. And around weeks 5 through 8, throughput dips, because they're doing the same work two ways: once their way, once with Claude. Plan for it.</p>
      <p><strong>They come out the other side feeling like they have superpowers.</strong> That's not a metaphor we use lightly. It's what demo day exists to prove.</p>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">Scope &amp; fit</div>
    <div class="prose">
      <h2>Scoped to your headcount. <em class="acc">Fixed fee, clear finish line.</em></h2>
      <p>The program scales from 2 to 3 departments for smaller companies up to 5 departments with an expanded champions network for larger ones. Above ~300 employees we scope custom. Every tier includes the pre-engagement diagnostic, the exec cohort, matched consultants, full context architecture, pair-programmed builds, and an exit handoff. We'll give you a real number on the first call.</p>
      <h2>Deployment or partnership? <em class="acc">How to choose.</em></h2>
      <p>The Deployment Program has a finish line: 16 weeks, your company live on Claude, your people shipping their own automations. It's the right fit when you want a defined transformation with a defined end, and your team is self-sufficient at exit.</p>
      <p><a href="fractional-caio.html" style="color: var(--terra);">Your AI Team</a> is the ongoing version: your AI lead owning the strategy, a dedicated engineer shipping every two weeks, training that never goes stale. Most deployment clients graduate into it, because the companies pulling ahead never stop building.</p>
    </div>
  </div>
</section>
"""
page("claude-deployment.html", "Claude Training & Deployment Program — Northwest AI", cdp)

# ============================================================ AI WORKSHOPS
workshops = """
<header class="page-hero">
  <div class="wrap">
    <div class="kicker">Programs &middot; AI Workshops</div>
    <h1>Get your team using AI. <em class="acc">In a day, not a quarter.</em></h1>
    <p class="lede">Hands-on workshops that make a team or a department fluent fast, on the work they actually do. The training on its own, without the full rollout.</p>
    <div class="hero-cta" style="margin-top: 32px;"><a class="btn terra" href="index.html#book">Book a discovery call</a></div>
  </div>
</header>

<section>
  <div class="wrap">
    <div class="kicker">Why it matters</div>
    <div class="prose">
      <h2>You don't have a tool problem. <em class="acc">You have an adoption problem.</em></h2>
      <p>Most rollouts stall around 15% of staff. Not because people are lazy, because nobody showed them what AI does for their specific job, and the tools move too fast to keep up with. A generic webinar doesn't fix that. Hands-on training on their real work does.</p>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">What you get</div>
    <h2 style="max-width: 800px;">Not a webinar. <em class="acc">Hands on their own work.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">01</div><h3>Built on your real work</h3><p>We train on the tasks your people actually do, not generic prompts.</p></div>
      <div class="step-v"><div class="num">02</div><h3>Role by role</h3><p>Finance, ops, sales: each group learns what AI does for their job.</p></div>
      <div class="step-v"><div class="num">03</div><h3>Skills that stick</h3><p>Your team leaves using AI on Monday, not just inspired by it.</p></div>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="kicker">Formats</div>
    <h2>One team or the whole company. <em class="acc">A day or a short run.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Length</div><h3>A day, or a few sessions</h3><p>Scoped to how much ground you want to cover.</p></div>
      <div class="step-v"><div class="num">Where</div><h3>On-site or remote</h3><p>Whatever fits your team.</p></div>
      <div class="step-v"><div class="num">Tools</div><h3>The best one for the job</h3><p>Claude, ChatGPT, whatever your team should actually be using.</p></div>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">Questions</div>
    <h2>The ones we <em class="acc">actually get.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Diff?</div><h3>"Is this the 16-week program?"</h3><p>No. That's the <a href="claude-deployment.html" style="color: var(--terra);">Claude Deployment Program</a>, company-wide, with builds and a Company Brain. Workshops are the focused, one-time version.</p></div>
      <div class="step-v"><div class="num">Skeptics?</div><h3>"Half my team won't care."</h3><p>That's exactly who we train. When it's their real work and their tools, the skeptics are the ones who convert.</p></div>
      <div class="step-v"><div class="num">More?</div><h3>"What if we want ongoing help?"</h3><p>Step up to <a href="fractional-caio.html" style="color: var(--terra);">Your AI Team</a> for a lead, an engineer, and a trainer every month.</p></div>
    </div>
  </div>
</section>
"""
page("workshops.html", "AI & Claude Workshops for Teams — Northwest AI", workshops)

# ============================================================ AI BUILDS
ai_builds = """
<header class="page-hero">
  <div class="wrap">
    <div class="kicker">Programs &middot; AI Builds</div>
    <h1>One system. Built right. <em class="acc">Fixed scope, fixed price.</em></h1>
    <p class="lede">When you need one specific thing built, a phone agent, an intake pipeline, an integration, we scope it, price it, and ship it. No retainer, no hourly meter.</p>
    <div class="hero-cta" style="margin-top: 32px;"><a class="btn terra" href="index.html#book">Book a discovery call</a></div>
  </div>
</header>

<section>
  <div class="wrap">
    <div class="kicker">What we build</div>
    <h2 style="max-width: 800px;">The stuff <em class="acc">off-the-shelf AI can't do.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Agents</div><h3>Phone and chat agents</h3><p>Answer calls and messages around the clock, hand the hard ones to a human.</p></div>
      <div class="step-v"><div class="num">Pipelines</div><h3>Intake and document pipelines</h3><p>Read, sort, classify, and route the work that piles up by hand.</p></div>
      <div class="step-v"><div class="num">Integrations</div><h3>Systems that finally talk</h3><p>Connect the tools that don't, so nobody enters the same data twice.</p></div>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">How it works</div>
    <h2>A quote, a build, <em class="acc">a finish line.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">01</div><h3>A fixed quote</h3><p>We scope the build and give you one price. No hourly meter.</p></div>
      <div class="step-v"><div class="num">02</div><h3>We build and ship it</h3><p>Our engineers build it, test it, and hand it over. You own every line.</p></div>
      <div class="step-v"><div class="num">03</div><h3>A clean handoff</h3><p>A defined deliverable with a defined end. It runs, and it is yours.</p></div>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="kicker">Proof</div>
    <h2 style="max-width: 800px;">Builds we've <em class="acc">actually shipped.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Healthcare</div><h3>HIPAA referral pipeline</h3><p>Sorting that ate hours a day, now minutes, tied into their EMR. <a href="case-study-referrals.html" style="color: var(--terra);">Read it &rarr;</a></p></div>
      <div class="step-v"><div class="num">Towing</div><h3>A 500-call-a-day phone agent</h3><p>Answers 90% of calls, around the clock. <a href="case-study-phone-agent.html" style="color: var(--terra);">Read it &rarr;</a></p></div>
      <div class="step-v"><div class="num">Construction</div><h3>Safety-report automation</h3><p>From 80% late to 80% on time. <a href="case-study-safety-reports.html" style="color: var(--terra);">Read it &rarr;</a></p></div>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">Is it a fit</div>
    <div class="prose">
      <h2>Best when you know <em class="acc">exactly what you need.</em></h2>
    </div>
    <div class="steps-vert">
      <div class="step-v"><div class="num">Good fit</div><h3>One clear problem</h3><p>A specific system you want built and owned, with a finish line.</p></div>
      <div class="step-v"><div class="num">Ongoing</div><h3>Need more than one</h3><p>If you want continuous build capacity, that is <a href="fractional-caio.html" style="color: var(--terra);">Your AI Team</a>.</p></div>
    </div>
  </div>
</section>
"""
page("ai-builds.html", "Custom AI Agent Development — Northwest AI", ai_builds)

# ============================================================ CASE STUDIES
def case_study(filename, kicker, h1, lede, stats, problem, built, result):
    body = """
<header class="page-hero">
  <div class="wrap">
    <div class="crumb"><a href="index.html">Home</a> / <a href="index.html#results">Results</a> / Case study</div>
    <div class="kicker">{K}</div>
    <h1>{H1}</h1>
    <p class="lede">{LEDE}</p>
  </div>
</header>
<section style="padding-top: 0; border-top: none;">
  <div class="wrap">
    <div class="stat-strip">{STATS}</div>
    <div class="prose">
      <h2>The problem</h2>
      {PROBLEM}
      <h2>What we built</h2>
      {BUILT}
      <h2>The result</h2>
      {RESULT}
    </div>
  </div>
</section>
""".replace("{K}", kicker).replace("{H1}", h1).replace("{LEDE}", lede).replace("{STATS}", stats).replace("{PROBLEM}", problem).replace("{BUILT}", built).replace("{RESULT}", result)
    page(filename, h1.replace('<em class="acc">', '').replace('</em>', '') + " — Northwest AI", body)

case_study(
  "case-study-referrals.html",
  "Case study &middot; Healthcare",
  'Insurance referrals: from hours of sorting to <em class="acc">minutes.</em>',
  "A healthcare provider's staff hand-sorted hundreds of insurance referrals. We automated the whole process.",
  """<div class="stat-cell"><div class="n">Hundreds</div><div class="l">of referrals processed</div></div>
     <div class="stat-cell"><div class="n">Hours &rarr; minutes</div><div class="l">processing time</div></div>
     <div class="stat-cell"><div class="n">HIPAA</div><div class="l">compliant, EMR-connected</div></div>""",
  """<p>Every referral that came in had to be read, classified, and routed by a person. Insurance referrals don't arrive in a tidy format: they show up as faxes, PDFs, and portal exports, each one different. Staff spent hours every day just sorting, before any actual care coordination happened.</p>
     <p>That's skilled people doing work a machine should do, and a queue that grows every time the practice grows.</p>""",
  """<p>We built an automated referral pipeline: incoming referrals get read, key details extracted, classified by type and urgency, and routed to the right queue, with a human reviewing the output instead of producing it.</p>
     <p><strong>The whole system is HIPAA compliant and connected to their EMR.</strong> Patient data stays protected end to end, and referrals land where care coordination actually happens, not in another inbox.</p>
     <p>It runs inside the team's existing workflow. Nobody learned new software. The work just shows up sorted.</p>""",
  """<p><strong>What took hours every day now takes minutes.</strong> The team reviews and handles exceptions instead of sorting from scratch, and referral volume can grow without the sorting burden growing with it.</p>"""
)

case_study(
  "case-study-phone-agent.html",
  "Case study &middot; Towing &amp; logistics",
  'A phone agent that answers <em class="acc">90% of 500 daily calls.</em>',
  "A towing company staffed a full call team to answer 500 calls a day. Our phone agent picks up almost all of them.",
  """<div class="stat-cell"><div class="n">500</div><div class="l">calls per day</div></div>
     <div class="stat-cell"><div class="n">90%</div><div class="l">answered by the agent</div></div>
     <div class="stat-cell"><div class="n">Towing</div><div class="l">industry</div></div>""",
  """<p>Five hundred calls a day, every day, answered by a human call team. Dispatch requests, status checks, the same questions on repeat. Staffing it meant constant hiring and training for high-turnover seats, and every missed call was potentially lost business.</p>""",
  """<p>We built a phone agent that answers the line, handles the routine calls end to end, and hands the unusual ones to a person with full context of the conversation so far.</p>
     <p>It picks up instantly, around the clock, and it doesn't have a bad day.</p>""",
  """<p><strong>The agent now picks up 90% of the company's 500 daily calls.</strong> The human team handles the calls that actually need a human, and the phone never rings out.</p>"""
)

case_study(
  "case-study-safety-reports.html",
  "Case study &middot; Construction",
  'Safety reports: from 80% late to <em class="acc">80% on time.</em>',
  "A construction company chased crews by hand for safety reports. Our automated system flipped the compliance rate.",
  """<div class="stat-cell"><div class="n">80% late</div><div class="l">before</div></div>
     <div class="stat-cell"><div class="n">80% on time</div><div class="l">after</div></div>
     <div class="stat-cell"><div class="n">Construction</div><div class="l">industry</div></div>""",
  """<p>Safety reports only protect you if they exist. Site teams are busy building, so reports slipped, and someone in the office spent their time chasing crews one by one. Eighty percent of reports came in late.</p>
     <p>In construction, that's not a paperwork problem. If there's ever an incident and a lawsuit, the company's defense is the documentation. Late and missing reports are exposure.</p>""",
  """<p>We built an automated system that pings every team member when their safety reports are due, follows up on its own, and gives leadership a live view of what's outstanding, without anyone playing collections agent.</p>""",
  """<p><strong>Safety reports went from 80% late to 80% on time.</strong> The documentation exists when it matters, the office got its time back, and leadership can see compliance at a glance instead of hoping.</p>"""
)

# ============================================================ ABOUT
about = """
<header class="page-hero">
  <div class="wrap">
    <div class="kicker">About Northwest AI</div>
    <h1>We make mid-market companies <em class="acc">AI native.</em></h1>
    <p class="lede">Northwest AI embeds engineers and consultants into companies doing $10M to $500M, builds their AI agents, trains their people, and runs their AI department. Bootstrapped, profitable, and built on shipped work, not slideware.</p>
  </div>
</header>

<section>
  <div class="wrap">
    <div class="kicker">What we believe</div>
    <div class="prose">
      <h2>The technology was never <em class="acc">the hard part.</em></h2>
      <p>MIT found that about 5% of enterprise AI pilots produce real P&amp;L impact. The other 95% spend and stall. We've watched why, from inside hundreds of engagements: AI fails on adoption, not capability. People get generic answers from a tool that doesn't know their company, and they quit.</p>
      <p>So we built the firm around the three things adoption actually takes: <strong>engineers who ship real builds, trainers who change daily behavior, and Company Brain, the context system that makes AI specific to your business from the first prompt.</strong> Most firms do one of these. Doing all three, every month, is the whole point.</p>
      <p>And we work where the big firms don't: the independent mid-market. Construction, insurance, healthcare, manufacturing. The companies that run the real economy, where the gap between AI talk and AI work is widest, and where closing it pays off fastest.</p>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">The story</div>
    <div class="prose">
      <h2>It started with a contract manager <em class="acc">in construction.</em></h2>
      <p>The engineering came first. Asad Malik and Awais Tariq started a software development firm in 2018, building custom tools for companies. When OpenAI opened its first API, their clients started asking for internal AI tools, so they built them. By the time the world was debating what AI might do someday, their team had been shipping it inside real businesses for years.</p>
      <p>The spark came later, from Wyatt's mom. She manages contracts for a construction company, and one day she was told she couldn't use AI. No training, no guidance, no legal help with the contracts crossing her desk every day. Just a ban.</p>
      <p>Wyatt had been building custom tools with Asad and Awais, and the contrast was hard to ignore. Inside the dev shop's world, AI was already doing real work. Outside it, the people who needed it most were being locked out, because nobody would teach them what it could do, what it couldn't, and how to use it safely. The problem was never the tool. It was that nobody was educating the people.</p>
      <p>So they bet the company on it. A hard pivot into AI: the 2018 engineering bench, plus consultants who teach in plain language, aimed at the companies everyone else ignores. That partnership became Northwest AI. The rest is history, and we've been building together ever since.</p>
    </div>
  </div>
</section>

<section>
  <div class="wrap">
    <div class="kicker">The team</div>
    <h2>Built by people who've <em class="acc">done it at scale.</em></h2>
    <div class="team-rows">
      <div class="team-row">
        <img class="face" src="https://nwai.co/wp-content/uploads/2025/07/wyatt-headshot-hq-2.png" alt="Wyatt Mayham">
        <div class="name">Wyatt Mayham</div>
        <div class="role">CEO</div>
        <p>Second-time founder. Built and sold TwitchMetrics to GameSquare (NASDAQ: GAME). Leads strategy and runs the front of the house.</p>
      </div>
      <div class="team-row">
        <img class="face" src="https://nwai.co/wp-content/uploads/2025/07/asad-headshot.jpg" alt="Asad Malik">
        <div class="name">Asad Malik</div>
        <div class="role">CTO</div>
        <p>Built the Thursday Night Football backend at Amazon. Owns technical strategy and hires and trains our engineers like AWS.</p>
      </div>
      <div class="team-row">
        <img class="face" src="https://nwai.co/wp-content/uploads/2025/07/awais-headshot.jpg" alt="Awais Tariq">
        <div class="name">Awais Tariq</div>
        <div class="role">COO</div>
        <p>Ex-Microsoft, Bank of America, and Merrill Lynch. Princeton grad. Fifteen years in operations. Runs delivery.</p>
      </div>
    </div>
    <p class="bench"><strong>Behind them:</strong> US-based consultants and trainers who own your relationship, and a 20-engineer team that ships around the clock.</p>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">How we work</div>
    <h2>Three rules we don't <em class="acc">break.</em></h2>
    <div class="steps-vert">
      <div class="step-v"><div class="num">01</div><h3>We build, not advise</h3><p>200+ shipped projects. Strategy exists to point the building in the right direction, never to replace it. You own every line we write.</p></div>
      <div class="step-v"><div class="num">02</div><h3>We say no</h3><p>Under $10M in revenue, we'll tell you the math doesn't work yet and point you to our free content. Turning away bad fits is how the guarantee stays easy to offer.</p></div>
      <div class="step-v"><div class="num">03</div><h3>We stay accountable</h3><p>Every engagement is backed by a 60-day money-back guarantee, and our flagship clients have grown with us year over year.</p></div>
    </div>
  </div>
</section>
"""
page("about.html", "About — Northwest AI", about)

# ============================================================ CAREERS
careers = """
<header class="page-hero">
  <div class="wrap">
    <div class="kicker">Careers</div>
    <h1>We hire people who know tech and can <em class="acc">talk to humans.</em></h1>
    <p class="lede">That combination is rarer than either skill alone, and it's the entire reason our clients' AI rollouts stick while everyone else's stall. If that sentence describes you, we should talk. <strong>We're always hiring for three roles.</strong></p>
  </div>
</header>

<section>
  <div class="wrap">
    <div class="kicker">Open roles</div>
    <div class="cards" style="margin-top: 36px;">
      <div class="card"><h3><a href="role-ai-consultant.html" style="color: inherit; text-decoration: none;">AI Consultant &rarr;</a></h3><p>Own client relationships and lead AI transformations inside mid-market companies. You've done a real job in a real industry, and you can teach.</p><p style="margin-top: 12px; font-size: 13px; color: var(--terra); font-weight: 600;">US-based &middot; Always open</p></div>
      <div class="card"><h3><a href="role-ai-trainer.html" style="color: inherit; text-decoration: none;">AI Trainer &rarr;</a></h3><p>Teach Claude to entire companies, role by role, from the exec cohort to the field. Adoption is behavior change, and you're the one who changes it.</p><p style="margin-top: 12px; font-size: 13px; color: var(--terra); font-weight: 600;">US-based &middot; Always open</p></div>
      <div class="card"><h3><a href="role-engineer.html" style="color: inherit; text-decoration: none;">Engineer &rarr;</a></h3><p>Ship agents, automations, and data pipelines that mid-market companies run their business on. Claude, MCP, and agentic workflows, in production.</p><p style="margin-top: 12px; font-size: 13px; color: var(--terra); font-weight: 600;">Remote &middot; Always open</p></div>
    </div>
  </div>
</section>

<section style="background: var(--paper-2);">
  <div class="wrap">
    <div class="kicker">Why here</div>
    <div class="prose">
      <h2>Real clients, real builds, <em class="acc">no bench time.</em></h2>
      <p>We're bootstrapped, profitable, and growing fast on the back of work that ships. You'll be inside real companies (construction, insurance, healthcare, manufacturing) doing work their teams use every day, not writing decks about work someone else might do someday.</p>
      <p>You'll also be early. The team is small, the surface area is huge, and the people who join now get to build the playbook everyone after them runs.</p>
    </div>
  </div>
</section>
"""
page("careers.html", "Careers — Northwest AI", careers, include_cta=False)

def role_page(filename, title, h1, lede, do_items, look_items, location):
    body = """
<header class="page-hero">
  <div class="wrap">
    <div class="crumb"><a href="careers.html">Careers</a> / {TITLE}</div>
    <div class="kicker">Open role &middot; {LOC}</div>
    <h1>{H1}</h1>
    <p class="lede">{LEDE}</p>
  </div>
</header>
<section style="padding-top: 0; border-top: none;">
  <div class="wrap">
    <div class="prose">
      <h2>What you'll do</h2>
      <ul>{DO}</ul>
      <h2>What we look for</h2>
      <ul>{LOOK}</ul>
      <h2>How to apply</h2>
      <p>Email <a href="mailto:wyatt@nwai.co?subject={SUBJ}" style="color: var(--terra);">wyatt@nwai.co</a> with the subject line "{TITLE}". Skip the formal cover letter. Send a few sentences on who you are, the most impressive thing you've built or taught, and why this role. If you've used Claude to do real work, tell us about that too.</p>
    </div>
  </div>
</section>
""".replace("{TITLE}", title).replace("{LOC}", location).replace("{H1}", h1).replace("{LEDE}", lede) \
   .replace("{DO}", "".join("<li>" + i + "</li>" for i in do_items)) \
   .replace("{LOOK}", "".join("<li>" + i + "</li>" for i in look_items)) \
   .replace("{SUBJ}", title.replace(" ", "%20"))
    page(filename, title + " — Careers — Northwest AI", body, include_cta=False)

role_page("role-ai-consultant.html", "AI Consultant",
  'You did the job for a decade. Now teach an industry <em class="acc">to do it with AI.</em>',
  "Our model pairs every client department with a consultant who actually worked in that discipline: finance with a finance veteran, ops with an ops veteran. You own client relationships, run discovery, and lead mid-market companies through becoming AI native.",
  ["Own a portfolio of client relationships as their day-to-day AI lead",
   "Run discovery and workflow mapping, and shape each client's 80/20 roadmap",
   "Pair-program real automations with client teams in your discipline",
   "Work alongside our engineers to turn what clients need into what gets built",
   "Represent NWAI in the room with executives, plainly and without jargon"],
  ["A real career in a real discipline: finance, operations, sales, marketing, supply chain, legal, or similar",
   "Daily, serious use of AI in your own work, you're the person colleagues already ask",
   "The rare combination: technical enough to be credible, human enough to be trusted",
   "Plain written and spoken communication, no consultant-speak",
   "Comfort with ambiguity, small-team pace, and being measured on client outcomes"],
  "US-based")

role_page("role-ai-trainer.html", "AI Trainer",
  "Adoption is behavior change. <em class='acc'>You're the one who changes it.</em>",
  "Most AI rollouts die because nobody actually teaches people. Our trainers run the 16-week programs that make whole companies fluent in AI, from the executive cohort to the field, on their real work.",
  ["Deliver Claude 101/102 and role-specific training across client departments",
   "Train executive cohorts in their language: budgets, board updates, deal memos",
   "Coach individuals through the learning curve, including the weeks where it's hard",
   "Run pair-programming sessions where client teams build their own automations",
   "Feed what you learn in the room back into our programs and playbooks"],
  ["You've taught adults something hard before: training, coaching, enablement, teaching, or facilitation",
   "Deep hands-on fluency with Claude, and the ability to demystify it for a skeptical operator who has done the job for 25 years",
   "Patience and presence in a room, in person and on Zoom",
   "Energy for repetition: the hundredth 101 session has to be as good as the first",
   "Plain language as a reflex, not an effort"],
  "US-based")

role_page("role-engineer.html", "Engineer",
  'Ship AI that companies <em class="acc">run their business on.</em>',
  "Our engineering team builds the agents, automations, and data pipelines behind every engagement: phone agents handling hundreds of calls a day, referral pipelines, safety systems, and Company Brain deployments. Real production work, shipped weekly, owned by the client.",
  ["Build and ship client automations: agents, integrations, data pipelines, and internal tools",
   "Stand up Company Brain deployments: source connectors, role mappings, sync infrastructure",
   "Work with Claude, MCP, and agentic workflows in production, not in demos",
   "Scope builds in plain language clients can approve, then deliver what was scoped",
   "Maintain what you ship: our clients stay, so your code has a long life"],
  ["Strong general software engineering: APIs, data, cloud infrastructure (AWS or Azure)",
   "Real experience building with LLMs and agentic patterns beyond toy projects",
   "Pragmatism: you ship the boring solution that works over the clever one that might",
   "Clear written communication, our team is distributed and async",
   "Comfort owning projects end to end with a small, senior team"],
  "Remote")

# ============================================================ LEGAL
privacy_body = """
<section class="page-hero" style="padding-bottom: 30px;"><div class="wrap legal">
<h1>Privacy Policy</h1>
<p class="updated">Last updated: January 2, 2025</p>
<h2>1. Information We Collect</h2>
<p>Northwest AI Consulting ("we," "us," or "our") collects information you provide directly to us, such as when you:</p>
<ul><li>Fill out contact forms or request consultations</li><li>Subscribe to our newsletters or communications</li><li>Participate in surveys or provide feedback</li><li>Contact us via email, phone, or other communication methods</li></ul>
<p>The types of information we may collect include:</p>
<ul><li>Name, email address, phone number, and company information</li><li>Project requirements and business information you choose to share</li><li>Communications between you and our team</li><li>Technical information about your AI implementation needs</li></ul>
<p>When you visit or log in to our website, cookies and similar technologies may be used by our online data partners or vendors to associate these activities with other personal information they or others have about you, including by association with your email or home address. We (or service providers on our behalf) may then send communications and marketing to these email or home addresses. You may opt out of receiving this advertising by visiting <a href="https://app.retention.com/optout">https://app.retention.com/optout</a>.</p>
<p>All the above categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.</p>
<h2>2. How We Use Your Information</h2>
<p>We use the information we collect to:</p>
<ul><li>Provide, maintain, and improve our AI consulting services</li><li>Respond to your inquiries and provide customer support</li><li>Send you technical updates, security alerts, and administrative messages</li><li>Develop custom AI solutions tailored to your business needs</li><li>Comply with legal obligations and protect our legal rights</li><li>Prevent fraud and enhance the security of our services</li></ul>
<h2>3. Information Sharing and Disclosure</h2>
<p>We do not sell, trade, or otherwise transfer your personal information to third parties except as described in this policy:</p>
<ul><li><strong>Service Providers:</strong> We may share information with trusted third-party service providers who assist us in operating our business</li><li><strong>Legal Requirements:</strong> We may disclose information if required by law or in response to valid legal requests</li><li><strong>Business Transfers:</strong> Information may be transferred in connection with mergers, acquisitions, or asset sales</li><li><strong>Consent:</strong> We may share information with your explicit consent</li></ul>
<h2>4. Data Security</h2>
<p>We implement appropriate technical and organizational security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. These measures include:</p>
<ul><li>Encryption of data in transit and at rest</li><li>Regular security assessments and updates</li><li>Access controls and authentication mechanisms</li><li>Employee training on data protection practices</li></ul>
<h2>5. Your Rights and Choices</h2>
<p>Depending on your location, you may have certain rights regarding your personal information:</p>
<ul><li><strong>Access:</strong> Request access to the personal information we hold about you</li><li><strong>Correction:</strong> Request correction of inaccurate or incomplete information</li><li><strong>Deletion:</strong> Request deletion of your personal information</li><li><strong>Portability:</strong> Request a copy of your information in a structured format</li><li><strong>Opt-out:</strong> Unsubscribe from marketing communications</li></ul>
<p>To exercise these rights, please contact us at consulting@nwai.co.</p>
<h2>6. Cookies and Tracking</h2>
<p>Our website may use cookies and similar tracking technologies to enhance your browsing experience and analyze website usage. You can control cookies through your browser settings.</p>
<h2>7. International Data Transfers</h2>
<p>Your information may be transferred to and processed in countries other than your country of residence. We ensure appropriate safeguards are in place to protect your information during such transfers.</p>
<h2>8. Changes to This Policy</h2>
<p>We may update this privacy policy from time to time. We will notify you of any material changes by posting the new policy on this page and updating the "Last updated" date.</p>
<h2>9. Contact Us</h2>
<p>If you have any questions about this privacy policy or our data practices, please contact us:</p>
<p><strong>Northwest AI Consulting</strong><br>Email: consulting@nwai.co<br>Phone: +1 (503) 298-4673</p>
</div></section>
"""
page("privacy.html", "Privacy Policy — Northwest AI", privacy_body, include_cta=False)

terms_body = """
<section class="page-hero" style="padding-bottom: 30px;"><div class="wrap legal">
<h1>Terms of Service</h1>
<p class="updated">Last updated: January 2, 2025</p>
<h2>1. Acceptance of Terms</h2>
<p>By accessing or using Northwest AI Consulting's website and services, you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our services.</p>
<h2>2. Description of Services</h2>
<p>Northwest AI Consulting provides artificial intelligence consulting services, including but not limited to:</p>
<ul><li>AI strategy development and roadmapping</li><li>Custom AI solution development and implementation</li><li>AI training and education programs</li><li>AI compliance and governance consulting</li><li>Managed AI services and ongoing support</li></ul>
<h2>3. User Responsibilities</h2>
<p>As a user of our services, you agree to:</p>
<ul><li>Provide accurate and complete information when requested</li><li>Maintain the confidentiality of any login credentials</li><li>Use our services only for lawful purposes</li><li>Respect intellectual property rights</li><li>Comply with all applicable laws and regulations</li><li>Not interfere with or disrupt our services</li></ul>
<h2>4. Service Availability</h2>
<p>We strive to maintain high availability of our services, but we do not guarantee uninterrupted access. We may temporarily suspend or restrict access for maintenance, updates, or other operational reasons.</p>
<h2>5. Intellectual Property</h2>
<p>All content, trademarks, and intellectual property on our website and in our services remain the property of Northwest AI Consulting or our licensors. You may not copy, modify, distribute, or create derivative works without explicit written permission.</p>
<p>Custom AI solutions developed for clients will be governed by separate consulting agreements that specify intellectual property ownership and usage rights.</p>
<h2>6. Confidentiality</h2>
<p>We understand the sensitive nature of business information shared during consulting engagements. We maintain strict confidentiality protocols and will not disclose your proprietary information without your explicit consent, except as required by law.</p>
<h2>7. Payment Terms</h2>
<p>Payment terms for consulting services will be specified in individual service agreements. General terms include:</p>
<ul><li>Fees are due according to the agreed payment schedule</li><li>Late payments may incur additional charges</li><li>All fees are non-refundable unless otherwise specified</li><li>Prices are subject to change with appropriate notice</li></ul>
<h2>8. Limitation of Liability</h2>
<p>To the fullest extent permitted by law, Northwest AI Consulting shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities.</p>
<p>Our total liability for any claims arising from our services shall not exceed the amount paid by you for the specific services giving rise to the claim.</p>
<h2>9. Disclaimers</h2>
<p>Our services are provided "as is" without warranties of any kind. We make no guarantees about the accuracy, reliability, or suitability of our AI solutions for specific purposes. AI technology involves inherent uncertainties, and results may vary.</p>
<h2>10. Termination</h2>
<p>Either party may terminate consulting agreements according to the terms specified in individual service contracts. We reserve the right to suspend or terminate access to our services for violations of these Terms.</p>
<h2>11. Governing Law</h2>
<p>These Terms shall be governed by and construed in accordance with the laws of the state in which Northwest AI Consulting is incorporated, without regard to conflict of law principles.</p>
<h2>12. Changes to Terms</h2>
<p>We may modify these Terms at any time by posting updated terms on our website. Your continued use of our services after such modifications constitutes acceptance of the new Terms.</p>
<h2>13. Contact Information</h2>
<p>If you have questions about these Terms, please contact us:</p>
<p><strong>Northwest AI Consulting</strong><br>Email: consulting@nwai.co<br>Phone: +1 (503) 298-4673</p>
</div></section>
"""
page("terms.html", "Terms of Service — Northwest AI", terms_body, include_cta=False)

# ============================================================ INDEX (adapt v3)
idx = v3
# replace inline style with stylesheet link
idx = re.sub(r"<style>.*?</style>", '<link rel="stylesheet" href="styles.css">', idx, flags=re.S)
# replace nav
idx = re.sub(r"<nav>.*?</nav>", NAV, idx, flags=re.S)
# replace footer
idx = re.sub(r"<footer>.*?</footer>", FOOTER, idx, flags=re.S)
# nav anchors within page still fine; fix nav links that pointed to anchors
idx = idx.replace('href="#brain"', 'href="company-brain.html"').replace('href="#programs"', 'href="#programs"')
# link results rows to case studies: add read links
idx = idx.replace(
  "now takes minutes.</p>",
  'now takes minutes, HIPAA compliant and connected to their EMR. <a href="case-study-referrals.html" style="color: var(--terra); font-weight: 600;">Read the case study &rarr;</a></p>')
idx = idx.replace(
  "now picks up 90% of them.</p>",
  'now picks up 90% of them. <a href="case-study-phone-agent.html" style="color: var(--terra); font-weight: 600;">Read the case study &rarr;</a></p>')
idx = idx.replace(
  "the paperwork exists.</strong></p>",
  'the paperwork exists.</strong> <a href="case-study-safety-reports.html" style="color: var(--terra); font-weight: 600;">Read the case study &rarr;</a></p>')
# link program cards
idx = idx.replace("<h3>Claude Deployment Program</h3>", '<h3><a href="claude-deployment.html" style="color: inherit; text-decoration: none;">Claude Deployment Program &rarr;</a></h3>')
idx = idx.replace("<h3>Fractional AI Team</h3>", '<h3><a href="fractional-caio.html" style="color: inherit; text-decoration: none;">Your AI Team &rarr;</a></h3>')
idx = idx.replace("<li>Your embedded AI department</li>", "<li>A dedicated engineer, an AI lead, and a trainer</li>")
idx = idx.replace("<li>Engineers, trainers, and a chief AI officer</li>", "<li>An engineer, a trainer, and your AI lead</li>")
idx = idx.replace("<li>Build credits included</li>", "<li>Two-week build sprints, you set priorities</li>")
idx = idx.replace("<h3>AI Workshops</h3>", '<h3><a href="workshops.html" style="color: inherit; text-decoration: none;">AI Workshops &rarr;</a></h3>')
# company brain section link to page
idx = idx.replace("We run it. Your team just opens Claude and it already knows the business.</p>",
  'We run it. Your team just opens Claude and it already knows the business. <a href="company-brain.html" style="color: var(--terra); font-weight: 600;">How Company Brain works &rarr;</a></p>')
# pricing off the math table (Wyatt 2026-06-10): "a whole lot less" + no recoverable 13x anchor
idx = idx.replace('<td>From $78K a year</td>', '<td>A whole lot less</td>')
idx = idx.replace('<p class="table-foot">Roughly <strong>13x cheaper</strong> than building it in-house.</p>',
  '<p class="table-foot">The real number depends on your size. We\'ll tell you on the first call, <strong>and it\'s a good one.</strong></p>')
# proof band rework (Wyatt 2026-06-10): since-2020 team cell leads, Amazon/Microsoft folds into its label
idx = re.sub(r'<div class="hero-proof">.*?</div>\s*</div>\s*</header>', """<div class="hero-proof">
      <div class="proof-item"><div class="n">Week 1</div><div class="l">Your team is live</div></div>
      <div class="proof-item"><div class="n">60-day</div><div class="l">Money-back guarantee</div></div>
      <div class="proof-item"><div class="n">15</div><div class="l">Engineers behind every client</div></div>
      <div class="proof-item"><div class="n">Since 2021</div><div class="l">Ex-Amazon &amp; Microsoft team shipping AI</div></div>
    </div>
  </div>
</header>""", idx, count=1, flags=re.S)
# result numerals: accent the after-state only (Wyatt 2026-06-10)
idx = idx.replace('<div class="n">Hours &rarr; minutes</div>', '<div class="n">Hours &rarr; <em>minutes</em></div>')
idx = idx.replace('<div class="n">90% of 500 daily calls</div>', '<div class="n"><em>90%</em> of 500 daily calls</div>')
idx = idx.replace('<div class="n">80% late &rarr; 80% on time</div>', '<div class="n">80% late &rarr; <em>80% on time</em></div>')
# client logo band removed until permission (Wyatt 2026-06-10)
idx = re.sub(r'<div class="trusted">.*?</div>\s*</div>\s*\n', '', idx, count=1, flags=re.S)
# headline revert per Wyatt (2026-06-09): back to the $1M payroll line
idx = idx.replace('<h1>AI doing real work, without hiring a <em class="acc">single engineer.</em></h1>',
  '<h1>Your AI department, without the <em class="acc">$1M payroll.</em></h1>')
idx = idx.replace("<title>Northwest AI — AI doing real work, without hiring a single engineer</title>",
  "<title>Fractional AI Team · Northwest AI</title>")
# deployment card bullet corrected per the real DSA program (no agents-by-week-4 claim)
idx = idx.replace("<li>Working agents by week four</li>", "<li>Pair-programmed builds and a demo day finish</li>")
# iClosed widget script + popup wiring on all booking CTAs
idx = idx.replace('<link rel="stylesheet" href="styles.css">',
  '<link rel="stylesheet" href="styles.css">\n<!-- iClosed popup widget begin -->\n<script type="text/javascript" src="https://app.iclosed.io/assets/widget.js" async></script>\n<!-- iClosed popup widget end -->')
idx = wire_booking(idx)
idx = idx.replace("wyatt@nwai.co", "consulting@nwai.co")
# SEO layer for index: separator swap, then meta/canonical/OG after the final title
idx = idx.replace("<title>Northwest AI — ", "<title>Northwest AI · ")
idx_title = re.search(r"<title>(.*?)</title>", idx).group(1)
idx = idx.replace("</title>", "</title>\n" + seo_tags("index.html", idx_title), 1)
# Homepage is built from the v3 mockup (its own <head>), so inject GTM + FB verification here too.
idx = re.sub(r"(<head[^>]*>)", lambda m: m.group(1) + "\n" + FAVICON + "\n" + FB_META + "\n" + GTM_HEAD, idx, count=1)
idx = re.sub(r"(<body[^>]*>)", lambda m: m.group(1) + "\n" + GTM_NOSCRIPT, idx, count=1)
idx = localize_faces(idx)
# Wrap the comparison table so it scrolls (readable column widths) on mobile instead of stacking skinny.
idx = idx.replace('<table>', '<div class="table-scroll"><table>').replace('</table>', '</table></div>')
open(os.path.join(OUT, "index.html"), "w").write(idx)
WRITTEN.append("index.html")
print("wrote index.html")

# ============================================================ ROBOTS + SITEMAP
robots = """User-agent: *
Allow: /

# /claude is the Facebook ads landing page. It carries meta noindex,nofollow.
# Do not Disallow it here: blocking crawl would hide that noindex tag from Google.

Sitemap: https://nwai.co/sitemap.xml
"""
open(os.path.join(OUT, "robots.txt"), "w").write(robots)
print("wrote robots.txt")

ordered = ["index.html"] + sorted(f for f in set(WRITTEN) if f != "index.html")
urls = "\n".join(
    "  <url>\n    <loc>%s</loc>\n    <lastmod>%s</lastmod>\n  </url>" % (page_url(f), TODAY)
    for f in ordered
)
sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n%s\n</urlset>\n' % urls
open(os.path.join(OUT, "sitemap.xml"), "w").write(sitemap)
print("wrote sitemap.xml (%d urls, /claude excluded by design)" % len(ordered))

# ---------------- /claude ads LP (the CAIO funnel page of record) ----------------
# Copied into the handoff as claude.html so the dev stands it up at nwai.co/claude.
# DELIBERATELY: not in the nav, not in the sitemap (it carries meta noindex,nofollow),
# and not SEO-tagged. Source of truth now lives in this folder (site/nwai-claude-lp-static.html).
lp = open(os.path.join(OUT, "nwai-claude-lp-static.html")).read()
# Carry the same GTM container + FB verification onto the /claude ads LP (matches live).
lp = re.sub(r"(<head[^>]*>)", lambda m: m.group(1) + "\n" + FAVICON + "\n" + FB_META + "\n" + GTM_HEAD, lp, count=1)
lp = re.sub(r"(<body[^>]*>)", lambda m: m.group(1) + "\n" + GTM_NOSCRIPT, lp, count=1)
open(os.path.join(OUT, "claude.html"), "w").write(lp)
print("wrote claude.html (ads LP, noindex, excluded from nav + sitemap)")

# ============================================================ ERROR PAGES (404 / 403)
# Funny, on-brand. Vercel auto-serves /404.html for unmatched routes. 403.html ships too
# (wire it via vercel.json if you want it served). Both are noindex and kept out of the sitemap.
ERR_TMPL = """
<section style="border-top:none;padding:110px 0;min-height:58vh;display:flex;align-items:center">
  <div class="wrap" style="text-align:center;margin:0 auto">
    <div class="kicker" style="justify-content:center">__EYEBROW__</div>
    <div style="font-family:'Fraunces',Georgia,serif;font-weight:600;font-size:clamp(110px,20vw,220px);line-height:.85;color:var(--terra);letter-spacing:-0.02em">__CODE__</div>
    <h1 style="margin-top:6px;max-width:760px;margin-left:auto;margin-right:auto">__HEADLINE__</h1>
    <p class="lede" style="margin:18px auto 0;max-width:540px">__SUB__</p>
    <div class="hero-cta" style="justify-content:center;margin-top:34px">
      <a class="btn terra" href="/">Back to the homepage</a>
      <a class="btn line" href="index.html#book">Book a call</a>
    </div>
  </div>
</section>
"""
def error_page(filename, code, eyebrow, headline_html, sub):
    body = (ERR_TMPL.replace("__EYEBROW__", eyebrow).replace("__CODE__", code)
            .replace("__HEADLINE__", headline_html).replace("__SUB__", sub))
    html = HEAD.replace("{{TITLE}}", code + " · Northwest AI").replace("{{SEO}}", '<meta name="robots" content="noindex,follow">')
    html += NAV + body + "\n<div style='height:60px'></div>\n" + FOOTER + "\n</body>\n</html>\n"
    html = wire_booking(html)
    html = html.replace("wyatt@nwai.co", "consulting@nwai.co")
    open(os.path.join(OUT, filename), "w").write(html)
    print("wrote", filename, "(custom error page, noindex, not in sitemap)")

error_page("404.html", "404", "404 · page not found",
    'This page got <em class="acc">automated out of a job.</em>',
    "The link is broken or the page moved. The parts that still do real work are one click away.")
error_page("403.html", "403", "403 · forbidden",
    'You need <em class="acc">clearance for this one.</em>',
    "This page is locked. No password needed to get back to the good stuff, though.")

print("DONE. Files:", sorted(os.listdir(OUT)))
